#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOSB.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DOSB")]
	public partial class CActivityDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCompletionActivityRelation(CompletionActivityRelation instance);
    partial void UpdateCompletionActivityRelation(CompletionActivityRelation instance);
    partial void DeleteCompletionActivityRelation(CompletionActivityRelation instance);
    partial void InsertClient(Client instance);
    partial void UpdateClient(Client instance);
    partial void DeleteClient(Client instance);
    partial void InsertCountry(Country instance);
    partial void UpdateCountry(Country instance);
    partial void DeleteCountry(Country instance);
    partial void InsertField(Field instance);
    partial void UpdateField(Field instance);
    partial void DeleteField(Field instance);
    partial void InsertWell(Well instance);
    partial void UpdateWell(Well instance);
    partial void DeleteWell(Well instance);
    partial void InsertWellType(WellType instance);
    partial void UpdateWellType(WellType instance);
    partial void DeleteWellType(WellType instance);
    partial void InsertCompletionActivity(CompletionActivity instance);
    partial void UpdateCompletionActivity(CompletionActivity instance);
    partial void DeleteCompletionActivity(CompletionActivity instance);
    partial void InsertCompletionType(CompletionType instance);
    partial void UpdateCompletionType(CompletionType instance);
    partial void DeleteCompletionType(CompletionType instance);
    partial void InsertRig(Rig instance);
    partial void UpdateRig(Rig instance);
    partial void DeleteRig(Rig instance);
    partial void InsertAssembly_Type(Assembly_Type instance);
    partial void UpdateAssembly_Type(Assembly_Type instance);
    partial void DeleteAssembly_Type(Assembly_Type instance);
    partial void InsertCompany(Company instance);
    partial void UpdateCompany(Company instance);
    partial void DeleteCompany(Company instance);
    #endregion
		
		public CActivityDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DOSBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CActivityDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CActivityDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CActivityDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CActivityDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CompletionActivityRelation> CompletionActivityRelations
		{
			get
			{
				return this.GetTable<CompletionActivityRelation>();
			}
		}
		
		public System.Data.Linq.Table<Client> Clients
		{
			get
			{
				return this.GetTable<Client>();
			}
		}
		
		public System.Data.Linq.Table<Country> Countries
		{
			get
			{
				return this.GetTable<Country>();
			}
		}
		
		public System.Data.Linq.Table<Field> Fields
		{
			get
			{
				return this.GetTable<Field>();
			}
		}
		
		public System.Data.Linq.Table<Well> Wells
		{
			get
			{
				return this.GetTable<Well>();
			}
		}
		
		public System.Data.Linq.Table<WellType> WellTypes
		{
			get
			{
				return this.GetTable<WellType>();
			}
		}
		
		public System.Data.Linq.Table<CompletionActivity> CompletionActivities
		{
			get
			{
				return this.GetTable<CompletionActivity>();
			}
		}
		
		public System.Data.Linq.Table<CompletionType> CompletionTypes
		{
			get
			{
				return this.GetTable<CompletionType>();
			}
		}
		
		public System.Data.Linq.Table<Rig> Rigs
		{
			get
			{
				return this.GetTable<Rig>();
			}
		}
		
		public System.Data.Linq.Table<vwCompActivity> vwCompActivities
		{
			get
			{
				return this.GetTable<vwCompActivity>();
			}
		}
		
		public System.Data.Linq.Table<vwLowerCompletionAssembly> vwLowerCompletionAssemblies
		{
			get
			{
				return this.GetTable<vwLowerCompletionAssembly>();
			}
		}
		
		public System.Data.Linq.Table<vwUpperCompletionAssembly> vwUpperCompletionAssemblies
		{
			get
			{
				return this.GetTable<vwUpperCompletionAssembly>();
			}
		}
		
		public System.Data.Linq.Table<Assembly_Type> Assembly_Types
		{
			get
			{
				return this.GetTable<Assembly_Type>();
			}
		}
		
		public System.Data.Linq.Table<Company> Companies
		{
			get
			{
				return this.GetTable<Company>();
			}
		}
		
		public System.Data.Linq.Table<vwCompletionActivityRelation> vwCompletionActivityRelations
		{
			get
			{
				return this.GetTable<vwCompletionActivityRelation>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CompletionActivityRelations")]
	public partial class CompletionActivityRelation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ActivityId;
		
		private int _CompanyId;
		
		private int _AssemblyTypeId;
		
		private System.Nullable<System.DateTime> _StartAt;
		
		private System.Nullable<System.DateTime> _FinishAt;
		
		private string _Comment;
		
		private System.Nullable<System.DateTime> _ShowAt;
		
		private EntityRef<CompletionActivity> _CompletionActivity;
		
		private EntityRef<Assembly_Type> _Assembly_Type;
		
		private EntityRef<Company> _Company;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnActivityIdChanging(int value);
    partial void OnActivityIdChanged();
    partial void OnCompanyIdChanging(int value);
    partial void OnCompanyIdChanged();
    partial void OnAssemblyTypeIdChanging(int value);
    partial void OnAssemblyTypeIdChanged();
    partial void OnStartAtChanging(System.Nullable<System.DateTime> value);
    partial void OnStartAtChanged();
    partial void OnFinishAtChanging(System.Nullable<System.DateTime> value);
    partial void OnFinishAtChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnShowAtChanging(System.Nullable<System.DateTime> value);
    partial void OnShowAtChanged();
    #endregion
		
		public CompletionActivityRelation()
		{
			this._CompletionActivity = default(EntityRef<CompletionActivity>);
			this._Assembly_Type = default(EntityRef<Assembly_Type>);
			this._Company = default(EntityRef<Company>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActivityId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ActivityId
		{
			get
			{
				return this._ActivityId;
			}
			set
			{
				if ((this._ActivityId != value))
				{
					if (this._CompletionActivity.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnActivityIdChanging(value);
					this.SendPropertyChanging();
					this._ActivityId = value;
					this.SendPropertyChanged("ActivityId");
					this.OnActivityIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CompanyId
		{
			get
			{
				return this._CompanyId;
			}
			set
			{
				if ((this._CompanyId != value))
				{
					if (this._Company.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCompanyIdChanging(value);
					this.SendPropertyChanging();
					this._CompanyId = value;
					this.SendPropertyChanged("CompanyId");
					this.OnCompanyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssemblyTypeId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int AssemblyTypeId
		{
			get
			{
				return this._AssemblyTypeId;
			}
			set
			{
				if ((this._AssemblyTypeId != value))
				{
					if (this._Assembly_Type.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAssemblyTypeIdChanging(value);
					this.SendPropertyChanging();
					this._AssemblyTypeId = value;
					this.SendPropertyChanged("AssemblyTypeId");
					this.OnAssemblyTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartAt", DbType="Date")]
		public System.Nullable<System.DateTime> StartAt
		{
			get
			{
				return this._StartAt;
			}
			set
			{
				if ((this._StartAt != value))
				{
					this.OnStartAtChanging(value);
					this.SendPropertyChanging();
					this._StartAt = value;
					this.SendPropertyChanged("StartAt");
					this.OnStartAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinishAt", DbType="Date")]
		public System.Nullable<System.DateTime> FinishAt
		{
			get
			{
				return this._FinishAt;
			}
			set
			{
				if ((this._FinishAt != value))
				{
					this.OnFinishAtChanging(value);
					this.SendPropertyChanging();
					this._FinishAt = value;
					this.SendPropertyChanged("FinishAt");
					this.OnFinishAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="VarChar(50)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowAt", DbType="Date")]
		public System.Nullable<System.DateTime> ShowAt
		{
			get
			{
				return this._ShowAt;
			}
			set
			{
				if ((this._ShowAt != value))
				{
					this.OnShowAtChanging(value);
					this.SendPropertyChanging();
					this._ShowAt = value;
					this.SendPropertyChanged("ShowAt");
					this.OnShowAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CompletionActivity_CompletionActivityRelation", Storage="_CompletionActivity", ThisKey="ActivityId", OtherKey="ActivityId", IsForeignKey=true)]
		public CompletionActivity CompletionActivity
		{
			get
			{
				return this._CompletionActivity.Entity;
			}
			set
			{
				CompletionActivity previousValue = this._CompletionActivity.Entity;
				if (((previousValue != value) 
							|| (this._CompletionActivity.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CompletionActivity.Entity = null;
						previousValue.CompletionActivityRelations.Remove(this);
					}
					this._CompletionActivity.Entity = value;
					if ((value != null))
					{
						value.CompletionActivityRelations.Add(this);
						this._ActivityId = value.ActivityId;
					}
					else
					{
						this._ActivityId = default(int);
					}
					this.SendPropertyChanged("CompletionActivity");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Assembly_Type_CompletionActivityRelation", Storage="_Assembly_Type", ThisKey="AssemblyTypeId", OtherKey="AssemblyType_Id", IsForeignKey=true)]
		public Assembly_Type Assembly_Type
		{
			get
			{
				return this._Assembly_Type.Entity;
			}
			set
			{
				Assembly_Type previousValue = this._Assembly_Type.Entity;
				if (((previousValue != value) 
							|| (this._Assembly_Type.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Assembly_Type.Entity = null;
						previousValue.CompletionActivityRelations.Remove(this);
					}
					this._Assembly_Type.Entity = value;
					if ((value != null))
					{
						value.CompletionActivityRelations.Add(this);
						this._AssemblyTypeId = value.AssemblyType_Id;
					}
					else
					{
						this._AssemblyTypeId = default(int);
					}
					this.SendPropertyChanged("Assembly_Type");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Company_CompletionActivityRelation", Storage="_Company", ThisKey="CompanyId", OtherKey="CompanyId", IsForeignKey=true)]
		public Company Company
		{
			get
			{
				return this._Company.Entity;
			}
			set
			{
				Company previousValue = this._Company.Entity;
				if (((previousValue != value) 
							|| (this._Company.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Company.Entity = null;
						previousValue.CompletionActivityRelations.Remove(this);
					}
					this._Company.Entity = value;
					if ((value != null))
					{
						value.CompletionActivityRelations.Add(this);
						this._CompanyId = value.CompanyId;
					}
					else
					{
						this._CompanyId = default(int);
					}
					this.SendPropertyChanged("Company");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Clients")]
	public partial class Client : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ClientId;
		
		private string _Name;
		
		private System.Nullable<int> _CountryId;
		
		private EntitySet<Field> _Fields;
		
		private EntityRef<Country> _Country;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnClientIdChanging(int value);
    partial void OnClientIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnCountryIdChanging(System.Nullable<int> value);
    partial void OnCountryIdChanged();
    #endregion
		
		public Client()
		{
			this._Fields = new EntitySet<Field>(new Action<Field>(this.attach_Fields), new Action<Field>(this.detach_Fields));
			this._Country = default(EntityRef<Country>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ClientId
		{
			get
			{
				return this._ClientId;
			}
			set
			{
				if ((this._ClientId != value))
				{
					this.OnClientIdChanging(value);
					this.SendPropertyChanging();
					this._ClientId = value;
					this.SendPropertyChanged("ClientId");
					this.OnClientIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryId", DbType="Int")]
		public System.Nullable<int> CountryId
		{
			get
			{
				return this._CountryId;
			}
			set
			{
				if ((this._CountryId != value))
				{
					if (this._Country.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCountryIdChanging(value);
					this.SendPropertyChanging();
					this._CountryId = value;
					this.SendPropertyChanged("CountryId");
					this.OnCountryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Client_Field", Storage="_Fields", ThisKey="ClientId", OtherKey="ClientId")]
		public EntitySet<Field> Fields
		{
			get
			{
				return this._Fields;
			}
			set
			{
				this._Fields.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Country_Client", Storage="_Country", ThisKey="CountryId", OtherKey="CountryId", IsForeignKey=true)]
		public Country Country
		{
			get
			{
				return this._Country.Entity;
			}
			set
			{
				Country previousValue = this._Country.Entity;
				if (((previousValue != value) 
							|| (this._Country.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Country.Entity = null;
						previousValue.Clients.Remove(this);
					}
					this._Country.Entity = value;
					if ((value != null))
					{
						value.Clients.Add(this);
						this._CountryId = value.CountryId;
					}
					else
					{
						this._CountryId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Country");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Fields(Field entity)
		{
			this.SendPropertyChanging();
			entity.Client = this;
		}
		
		private void detach_Fields(Field entity)
		{
			this.SendPropertyChanging();
			entity.Client = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Countries")]
	public partial class Country : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CountryId;
		
		private string _Name;
		
		private EntitySet<Client> _Clients;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCountryIdChanging(int value);
    partial void OnCountryIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public Country()
		{
			this._Clients = new EntitySet<Client>(new Action<Client>(this.attach_Clients), new Action<Client>(this.detach_Clients));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CountryId
		{
			get
			{
				return this._CountryId;
			}
			set
			{
				if ((this._CountryId != value))
				{
					this.OnCountryIdChanging(value);
					this.SendPropertyChanging();
					this._CountryId = value;
					this.SendPropertyChanged("CountryId");
					this.OnCountryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Country_Client", Storage="_Clients", ThisKey="CountryId", OtherKey="CountryId")]
		public EntitySet<Client> Clients
		{
			get
			{
				return this._Clients;
			}
			set
			{
				this._Clients.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Clients(Client entity)
		{
			this.SendPropertyChanging();
			entity.Country = this;
		}
		
		private void detach_Clients(Client entity)
		{
			this.SendPropertyChanging();
			entity.Country = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fields")]
	public partial class Field : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FieldId;
		
		private string _Name;
		
		private System.Nullable<int> _ClientId;
		
		private EntitySet<Well> _Wells;
		
		private EntityRef<Client> _Client;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFieldIdChanging(int value);
    partial void OnFieldIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnClientIdChanging(System.Nullable<int> value);
    partial void OnClientIdChanged();
    #endregion
		
		public Field()
		{
			this._Wells = new EntitySet<Well>(new Action<Well>(this.attach_Wells), new Action<Well>(this.detach_Wells));
			this._Client = default(EntityRef<Client>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FieldId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int FieldId
		{
			get
			{
				return this._FieldId;
			}
			set
			{
				if ((this._FieldId != value))
				{
					this.OnFieldIdChanging(value);
					this.SendPropertyChanging();
					this._FieldId = value;
					this.SendPropertyChanged("FieldId");
					this.OnFieldIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientId", DbType="Int")]
		public System.Nullable<int> ClientId
		{
			get
			{
				return this._ClientId;
			}
			set
			{
				if ((this._ClientId != value))
				{
					if (this._Client.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnClientIdChanging(value);
					this.SendPropertyChanging();
					this._ClientId = value;
					this.SendPropertyChanged("ClientId");
					this.OnClientIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Field_Well", Storage="_Wells", ThisKey="FieldId", OtherKey="FieldId")]
		public EntitySet<Well> Wells
		{
			get
			{
				return this._Wells;
			}
			set
			{
				this._Wells.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Client_Field", Storage="_Client", ThisKey="ClientId", OtherKey="ClientId", IsForeignKey=true)]
		public Client Client
		{
			get
			{
				return this._Client.Entity;
			}
			set
			{
				Client previousValue = this._Client.Entity;
				if (((previousValue != value) 
							|| (this._Client.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Client.Entity = null;
						previousValue.Fields.Remove(this);
					}
					this._Client.Entity = value;
					if ((value != null))
					{
						value.Fields.Add(this);
						this._ClientId = value.ClientId;
					}
					else
					{
						this._ClientId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Client");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Wells(Well entity)
		{
			this.SendPropertyChanging();
			entity.Field = this;
		}
		
		private void detach_Wells(Well entity)
		{
			this.SendPropertyChanging();
			entity.Field = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Wells")]
	public partial class Well : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _WellId;
		
		private string _Name;
		
		private System.Nullable<int> _FieldId;
		
		private string _Status;
		
		private System.Nullable<int> _TypeId;
		
		private EntitySet<CompletionActivity> _CompletionActivities;
		
		private EntityRef<Field> _Field;
		
		private EntityRef<WellType> _WellType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWellIdChanging(int value);
    partial void OnWellIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnFieldIdChanging(System.Nullable<int> value);
    partial void OnFieldIdChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnTypeIdChanging(System.Nullable<int> value);
    partial void OnTypeIdChanged();
    #endregion
		
		public Well()
		{
			this._CompletionActivities = new EntitySet<CompletionActivity>(new Action<CompletionActivity>(this.attach_CompletionActivities), new Action<CompletionActivity>(this.detach_CompletionActivities));
			this._Field = default(EntityRef<Field>);
			this._WellType = default(EntityRef<WellType>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WellId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int WellId
		{
			get
			{
				return this._WellId;
			}
			set
			{
				if ((this._WellId != value))
				{
					this.OnWellIdChanging(value);
					this.SendPropertyChanging();
					this._WellId = value;
					this.SendPropertyChanged("WellId");
					this.OnWellIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FieldId", DbType="Int")]
		public System.Nullable<int> FieldId
		{
			get
			{
				return this._FieldId;
			}
			set
			{
				if ((this._FieldId != value))
				{
					if (this._Field.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFieldIdChanging(value);
					this.SendPropertyChanging();
					this._FieldId = value;
					this.SendPropertyChanged("FieldId");
					this.OnFieldIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeId", DbType="Int")]
		public System.Nullable<int> TypeId
		{
			get
			{
				return this._TypeId;
			}
			set
			{
				if ((this._TypeId != value))
				{
					if (this._WellType.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTypeIdChanging(value);
					this.SendPropertyChanging();
					this._TypeId = value;
					this.SendPropertyChanged("TypeId");
					this.OnTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Well_CompletionActivity", Storage="_CompletionActivities", ThisKey="WellId", OtherKey="WellId")]
		public EntitySet<CompletionActivity> CompletionActivities
		{
			get
			{
				return this._CompletionActivities;
			}
			set
			{
				this._CompletionActivities.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Field_Well", Storage="_Field", ThisKey="FieldId", OtherKey="FieldId", IsForeignKey=true)]
		public Field Field
		{
			get
			{
				return this._Field.Entity;
			}
			set
			{
				Field previousValue = this._Field.Entity;
				if (((previousValue != value) 
							|| (this._Field.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Field.Entity = null;
						previousValue.Wells.Remove(this);
					}
					this._Field.Entity = value;
					if ((value != null))
					{
						value.Wells.Add(this);
						this._FieldId = value.FieldId;
					}
					else
					{
						this._FieldId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Field");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WellType_Well", Storage="_WellType", ThisKey="TypeId", OtherKey="WellTypeId", IsForeignKey=true)]
		public WellType WellType
		{
			get
			{
				return this._WellType.Entity;
			}
			set
			{
				WellType previousValue = this._WellType.Entity;
				if (((previousValue != value) 
							|| (this._WellType.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._WellType.Entity = null;
						previousValue.Wells.Remove(this);
					}
					this._WellType.Entity = value;
					if ((value != null))
					{
						value.Wells.Add(this);
						this._TypeId = value.WellTypeId;
					}
					else
					{
						this._TypeId = default(Nullable<int>);
					}
					this.SendPropertyChanged("WellType");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CompletionActivities(CompletionActivity entity)
		{
			this.SendPropertyChanging();
			entity.Well = this;
		}
		
		private void detach_CompletionActivities(CompletionActivity entity)
		{
			this.SendPropertyChanging();
			entity.Well = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WellTypes")]
	public partial class WellType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _WellTypeId;
		
		private string _Name;
		
		private EntitySet<Well> _Wells;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWellTypeIdChanging(int value);
    partial void OnWellTypeIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public WellType()
		{
			this._Wells = new EntitySet<Well>(new Action<Well>(this.attach_Wells), new Action<Well>(this.detach_Wells));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WellTypeId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int WellTypeId
		{
			get
			{
				return this._WellTypeId;
			}
			set
			{
				if ((this._WellTypeId != value))
				{
					this.OnWellTypeIdChanging(value);
					this.SendPropertyChanging();
					this._WellTypeId = value;
					this.SendPropertyChanged("WellTypeId");
					this.OnWellTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WellType_Well", Storage="_Wells", ThisKey="WellTypeId", OtherKey="TypeId")]
		public EntitySet<Well> Wells
		{
			get
			{
				return this._Wells;
			}
			set
			{
				this._Wells.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Wells(Well entity)
		{
			this.SendPropertyChanging();
			entity.WellType = this;
		}
		
		private void detach_Wells(Well entity)
		{
			this.SendPropertyChanging();
			entity.WellType = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CompletionActivities")]
	public partial class CompletionActivity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ActivityId;
		
		private System.Nullable<int> _RigId;
		
		private System.Nullable<int> _WellId;
		
		private System.Nullable<int> _CompletionTypeId;
		
		private System.Nullable<System.DateTime> _StartAt;
		
		private System.Nullable<System.DateTime> _FinishAt;
		
		private System.Nullable<System.DateTime> _ShowAt;
		
		private string _Comment;
		
		private EntitySet<CompletionActivityRelation> _CompletionActivityRelations;
		
		private EntityRef<Well> _Well;
		
		private EntityRef<CompletionType> _CompletionType;
		
		private EntityRef<Rig> _Rig;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnActivityIdChanging(int value);
    partial void OnActivityIdChanged();
    partial void OnRigIdChanging(System.Nullable<int> value);
    partial void OnRigIdChanged();
    partial void OnWellIdChanging(System.Nullable<int> value);
    partial void OnWellIdChanged();
    partial void OnCompletionTypeIdChanging(System.Nullable<int> value);
    partial void OnCompletionTypeIdChanged();
    partial void OnStartAtChanging(System.Nullable<System.DateTime> value);
    partial void OnStartAtChanged();
    partial void OnFinishAtChanging(System.Nullable<System.DateTime> value);
    partial void OnFinishAtChanged();
    partial void OnShowAtChanging(System.Nullable<System.DateTime> value);
    partial void OnShowAtChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    #endregion
		
		public CompletionActivity()
		{
			this._CompletionActivityRelations = new EntitySet<CompletionActivityRelation>(new Action<CompletionActivityRelation>(this.attach_CompletionActivityRelations), new Action<CompletionActivityRelation>(this.detach_CompletionActivityRelations));
			this._Well = default(EntityRef<Well>);
			this._CompletionType = default(EntityRef<CompletionType>);
			this._Rig = default(EntityRef<Rig>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActivityId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ActivityId
		{
			get
			{
				return this._ActivityId;
			}
			set
			{
				if ((this._ActivityId != value))
				{
					this.OnActivityIdChanging(value);
					this.SendPropertyChanging();
					this._ActivityId = value;
					this.SendPropertyChanged("ActivityId");
					this.OnActivityIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RigId", DbType="Int")]
		public System.Nullable<int> RigId
		{
			get
			{
				return this._RigId;
			}
			set
			{
				if ((this._RigId != value))
				{
					if (this._Rig.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRigIdChanging(value);
					this.SendPropertyChanging();
					this._RigId = value;
					this.SendPropertyChanged("RigId");
					this.OnRigIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WellId", DbType="Int")]
		public System.Nullable<int> WellId
		{
			get
			{
				return this._WellId;
			}
			set
			{
				if ((this._WellId != value))
				{
					if (this._Well.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnWellIdChanging(value);
					this.SendPropertyChanging();
					this._WellId = value;
					this.SendPropertyChanged("WellId");
					this.OnWellIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompletionTypeId", DbType="Int")]
		public System.Nullable<int> CompletionTypeId
		{
			get
			{
				return this._CompletionTypeId;
			}
			set
			{
				if ((this._CompletionTypeId != value))
				{
					if (this._CompletionType.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCompletionTypeIdChanging(value);
					this.SendPropertyChanging();
					this._CompletionTypeId = value;
					this.SendPropertyChanged("CompletionTypeId");
					this.OnCompletionTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartAt", DbType="Date")]
		public System.Nullable<System.DateTime> StartAt
		{
			get
			{
				return this._StartAt;
			}
			set
			{
				if ((this._StartAt != value))
				{
					this.OnStartAtChanging(value);
					this.SendPropertyChanging();
					this._StartAt = value;
					this.SendPropertyChanged("StartAt");
					this.OnStartAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinishAt", DbType="Date")]
		public System.Nullable<System.DateTime> FinishAt
		{
			get
			{
				return this._FinishAt;
			}
			set
			{
				if ((this._FinishAt != value))
				{
					this.OnFinishAtChanging(value);
					this.SendPropertyChanging();
					this._FinishAt = value;
					this.SendPropertyChanged("FinishAt");
					this.OnFinishAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowAt", DbType="Date")]
		public System.Nullable<System.DateTime> ShowAt
		{
			get
			{
				return this._ShowAt;
			}
			set
			{
				if ((this._ShowAt != value))
				{
					this.OnShowAtChanging(value);
					this.SendPropertyChanging();
					this._ShowAt = value;
					this.SendPropertyChanged("ShowAt");
					this.OnShowAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="VarChar(MAX)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CompletionActivity_CompletionActivityRelation", Storage="_CompletionActivityRelations", ThisKey="ActivityId", OtherKey="ActivityId")]
		public EntitySet<CompletionActivityRelation> CompletionActivityRelations
		{
			get
			{
				return this._CompletionActivityRelations;
			}
			set
			{
				this._CompletionActivityRelations.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Well_CompletionActivity", Storage="_Well", ThisKey="WellId", OtherKey="WellId", IsForeignKey=true)]
		public Well Well
		{
			get
			{
				return this._Well.Entity;
			}
			set
			{
				Well previousValue = this._Well.Entity;
				if (((previousValue != value) 
							|| (this._Well.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Well.Entity = null;
						previousValue.CompletionActivities.Remove(this);
					}
					this._Well.Entity = value;
					if ((value != null))
					{
						value.CompletionActivities.Add(this);
						this._WellId = value.WellId;
					}
					else
					{
						this._WellId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Well");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CompletionType_CompletionActivity", Storage="_CompletionType", ThisKey="CompletionTypeId", OtherKey="CompletionTypeId", IsForeignKey=true)]
		public CompletionType CompletionType
		{
			get
			{
				return this._CompletionType.Entity;
			}
			set
			{
				CompletionType previousValue = this._CompletionType.Entity;
				if (((previousValue != value) 
							|| (this._CompletionType.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CompletionType.Entity = null;
						previousValue.CompletionActivities.Remove(this);
					}
					this._CompletionType.Entity = value;
					if ((value != null))
					{
						value.CompletionActivities.Add(this);
						this._CompletionTypeId = value.CompletionTypeId;
					}
					else
					{
						this._CompletionTypeId = default(Nullable<int>);
					}
					this.SendPropertyChanged("CompletionType");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rig_CompletionActivity", Storage="_Rig", ThisKey="RigId", OtherKey="RigId", IsForeignKey=true)]
		public Rig Rig
		{
			get
			{
				return this._Rig.Entity;
			}
			set
			{
				Rig previousValue = this._Rig.Entity;
				if (((previousValue != value) 
							|| (this._Rig.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Rig.Entity = null;
						previousValue.CompletionActivities.Remove(this);
					}
					this._Rig.Entity = value;
					if ((value != null))
					{
						value.CompletionActivities.Add(this);
						this._RigId = value.RigId;
					}
					else
					{
						this._RigId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Rig");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CompletionActivityRelations(CompletionActivityRelation entity)
		{
			this.SendPropertyChanging();
			entity.CompletionActivity = this;
		}
		
		private void detach_CompletionActivityRelations(CompletionActivityRelation entity)
		{
			this.SendPropertyChanging();
			entity.CompletionActivity = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CompletionTypes")]
	public partial class CompletionType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CompletionTypeId;
		
		private string _Name;
		
		private EntitySet<CompletionActivity> _CompletionActivities;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCompletionTypeIdChanging(int value);
    partial void OnCompletionTypeIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public CompletionType()
		{
			this._CompletionActivities = new EntitySet<CompletionActivity>(new Action<CompletionActivity>(this.attach_CompletionActivities), new Action<CompletionActivity>(this.detach_CompletionActivities));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompletionTypeId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CompletionTypeId
		{
			get
			{
				return this._CompletionTypeId;
			}
			set
			{
				if ((this._CompletionTypeId != value))
				{
					this.OnCompletionTypeIdChanging(value);
					this.SendPropertyChanging();
					this._CompletionTypeId = value;
					this.SendPropertyChanged("CompletionTypeId");
					this.OnCompletionTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CompletionType_CompletionActivity", Storage="_CompletionActivities", ThisKey="CompletionTypeId", OtherKey="CompletionTypeId")]
		public EntitySet<CompletionActivity> CompletionActivities
		{
			get
			{
				return this._CompletionActivities;
			}
			set
			{
				this._CompletionActivities.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CompletionActivities(CompletionActivity entity)
		{
			this.SendPropertyChanging();
			entity.CompletionType = this;
		}
		
		private void detach_CompletionActivities(CompletionActivity entity)
		{
			this.SendPropertyChanging();
			entity.CompletionType = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rigs")]
	public partial class Rig : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RigId;
		
		private string _Name;
		
		private string _Type;
		
		private EntitySet<CompletionActivity> _CompletionActivities;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRigIdChanging(int value);
    partial void OnRigIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    #endregion
		
		public Rig()
		{
			this._CompletionActivities = new EntitySet<CompletionActivity>(new Action<CompletionActivity>(this.attach_CompletionActivities), new Action<CompletionActivity>(this.detach_CompletionActivities));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RigId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RigId
		{
			get
			{
				return this._RigId;
			}
			set
			{
				if ((this._RigId != value))
				{
					this.OnRigIdChanging(value);
					this.SendPropertyChanging();
					this._RigId = value;
					this.SendPropertyChanged("RigId");
					this.OnRigIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(50)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rig_CompletionActivity", Storage="_CompletionActivities", ThisKey="RigId", OtherKey="RigId")]
		public EntitySet<CompletionActivity> CompletionActivities
		{
			get
			{
				return this._CompletionActivities;
			}
			set
			{
				this._CompletionActivities.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CompletionActivities(CompletionActivity entity)
		{
			this.SendPropertyChanging();
			entity.Rig = this;
		}
		
		private void detach_CompletionActivities(CompletionActivity entity)
		{
			this.SendPropertyChanging();
			entity.Rig = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vwCompActivity")]
	public partial class vwCompActivity
	{
		
		private string _FieldName;
		
		private string _ClientName;
		
		private string _CountryName;
		
		private string _Comment;
		
		private string _RigName;
		
		private string _WellName;
		
		private string _WellStatus;
		
		private string _WellTypeName;
		
		private string _CompTypeName;
		
		private int _ActivityId;
		
		public vwCompActivity()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FieldName", DbType="NVarChar(50)")]
		public string FieldName
		{
			get
			{
				return this._FieldName;
			}
			set
			{
				if ((this._FieldName != value))
				{
					this._FieldName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientName", DbType="NVarChar(50)")]
		public string ClientName
		{
			get
			{
				return this._ClientName;
			}
			set
			{
				if ((this._ClientName != value))
				{
					this._ClientName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryName", DbType="VarChar(50)")]
		public string CountryName
		{
			get
			{
				return this._CountryName;
			}
			set
			{
				if ((this._CountryName != value))
				{
					this._CountryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="VarChar(MAX)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this._Comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RigName", DbType="VarChar(50)")]
		public string RigName
		{
			get
			{
				return this._RigName;
			}
			set
			{
				if ((this._RigName != value))
				{
					this._RigName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WellName", DbType="NVarChar(50)")]
		public string WellName
		{
			get
			{
				return this._WellName;
			}
			set
			{
				if ((this._WellName != value))
				{
					this._WellName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WellStatus", DbType="VarChar(50)")]
		public string WellStatus
		{
			get
			{
				return this._WellStatus;
			}
			set
			{
				if ((this._WellStatus != value))
				{
					this._WellStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WellTypeName", DbType="VarChar(50)")]
		public string WellTypeName
		{
			get
			{
				return this._WellTypeName;
			}
			set
			{
				if ((this._WellTypeName != value))
				{
					this._WellTypeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompTypeName", DbType="VarChar(50)")]
		public string CompTypeName
		{
			get
			{
				return this._CompTypeName;
			}
			set
			{
				if ((this._CompTypeName != value))
				{
					this._CompTypeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActivityId", DbType="Int NOT NULL")]
		public int ActivityId
		{
			get
			{
				return this._ActivityId;
			}
			set
			{
				if ((this._ActivityId != value))
				{
					this._ActivityId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vwLowerCompletionAssembly")]
	public partial class vwLowerCompletionAssembly
	{
		
		private int _AssemblyTypeId;
		
		private string _AssemblyName;
		
		private string _ComletionType;
		
		public vwLowerCompletionAssembly()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="AssemblyTypeId", Storage="_AssemblyTypeId", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int AssemblyType_Id
		{
			get
			{
				return this._AssemblyTypeId;
			}
			set
			{
				if ((this._AssemblyTypeId != value))
				{
					this._AssemblyTypeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="AssemblyName", Storage="_AssemblyName", DbType="NVarChar(50)")]
		public string Assembly_Name
		{
			get
			{
				return this._AssemblyName;
			}
			set
			{
				if ((this._AssemblyName != value))
				{
					this._AssemblyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ComletionType", Storage="_ComletionType", DbType="NVarChar(50)")]
		public string Comletion_Type
		{
			get
			{
				return this._ComletionType;
			}
			set
			{
				if ((this._ComletionType != value))
				{
					this._ComletionType = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vwUpperCompletionAssembly")]
	public partial class vwUpperCompletionAssembly
	{
		
		private int _AssemblyTypeId;
		
		private string _AssemblyName;
		
		private string _ComletionType;
		
		public vwUpperCompletionAssembly()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="AssemblyTypeId", Storage="_AssemblyTypeId", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int AssemblyType_Id
		{
			get
			{
				return this._AssemblyTypeId;
			}
			set
			{
				if ((this._AssemblyTypeId != value))
				{
					this._AssemblyTypeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="AssemblyName", Storage="_AssemblyName", DbType="NVarChar(50)")]
		public string Assembly_Name
		{
			get
			{
				return this._AssemblyName;
			}
			set
			{
				if ((this._AssemblyName != value))
				{
					this._AssemblyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ComletionType", Storage="_ComletionType", DbType="NVarChar(50)")]
		public string Comletion_Type
		{
			get
			{
				return this._ComletionType;
			}
			set
			{
				if ((this._ComletionType != value))
				{
					this._ComletionType = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AssemblyType")]
	public partial class Assembly_Type : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AssemblyType_Id;
		
		private string _Assembly_Name;
		
		private string _Comletion_Type;
		
		private EntitySet<CompletionActivityRelation> _CompletionActivityRelations;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAssemblyType_IdChanging(int value);
    partial void OnAssemblyType_IdChanged();
    partial void OnAssembly_NameChanging(string value);
    partial void OnAssembly_NameChanged();
    partial void OnComletion_TypeChanging(string value);
    partial void OnComletion_TypeChanged();
    #endregion
		
		public Assembly_Type()
		{
			this._CompletionActivityRelations = new EntitySet<CompletionActivityRelation>(new Action<CompletionActivityRelation>(this.attach_CompletionActivityRelations), new Action<CompletionActivityRelation>(this.detach_CompletionActivityRelations));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="AssemblyTypeId", Storage="_AssemblyType_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AssemblyType_Id
		{
			get
			{
				return this._AssemblyType_Id;
			}
			set
			{
				if ((this._AssemblyType_Id != value))
				{
					this.OnAssemblyType_IdChanging(value);
					this.SendPropertyChanging();
					this._AssemblyType_Id = value;
					this.SendPropertyChanged("AssemblyType_Id");
					this.OnAssemblyType_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="AssemblyName", Storage="_Assembly_Name", DbType="NVarChar(50)")]
		public string Assembly_Name
		{
			get
			{
				return this._Assembly_Name;
			}
			set
			{
				if ((this._Assembly_Name != value))
				{
					this.OnAssembly_NameChanging(value);
					this.SendPropertyChanging();
					this._Assembly_Name = value;
					this.SendPropertyChanged("Assembly_Name");
					this.OnAssembly_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ComletionType", Storage="_Comletion_Type", DbType="NVarChar(50)")]
		public string Comletion_Type
		{
			get
			{
				return this._Comletion_Type;
			}
			set
			{
				if ((this._Comletion_Type != value))
				{
					this.OnComletion_TypeChanging(value);
					this.SendPropertyChanging();
					this._Comletion_Type = value;
					this.SendPropertyChanged("Comletion_Type");
					this.OnComletion_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Assembly_Type_CompletionActivityRelation", Storage="_CompletionActivityRelations", ThisKey="AssemblyType_Id", OtherKey="AssemblyTypeId")]
		public EntitySet<CompletionActivityRelation> CompletionActivityRelations
		{
			get
			{
				return this._CompletionActivityRelations;
			}
			set
			{
				this._CompletionActivityRelations.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CompletionActivityRelations(CompletionActivityRelation entity)
		{
			this.SendPropertyChanging();
			entity.Assembly_Type = this;
		}
		
		private void detach_CompletionActivityRelations(CompletionActivityRelation entity)
		{
			this.SendPropertyChanging();
			entity.Assembly_Type = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Companies")]
	public partial class Company : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CompanyId;
		
		private string _ShortName;
		
		private string _FullName;
		
		private string _CompaneColor;
		
		private string _TextColor;
		
		private EntitySet<CompletionActivityRelation> _CompletionActivityRelations;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCompanyIdChanging(int value);
    partial void OnCompanyIdChanged();
    partial void OnShortNameChanging(string value);
    partial void OnShortNameChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnCompaneColorChanging(string value);
    partial void OnCompaneColorChanged();
    partial void OnTextColorChanging(string value);
    partial void OnTextColorChanged();
    #endregion
		
		public Company()
		{
			this._CompletionActivityRelations = new EntitySet<CompletionActivityRelation>(new Action<CompletionActivityRelation>(this.attach_CompletionActivityRelations), new Action<CompletionActivityRelation>(this.detach_CompletionActivityRelations));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CompanyId
		{
			get
			{
				return this._CompanyId;
			}
			set
			{
				if ((this._CompanyId != value))
				{
					this.OnCompanyIdChanging(value);
					this.SendPropertyChanging();
					this._CompanyId = value;
					this.SendPropertyChanged("CompanyId");
					this.OnCompanyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortName", DbType="VarChar(50)")]
		public string ShortName
		{
			get
			{
				return this._ShortName;
			}
			set
			{
				if ((this._ShortName != value))
				{
					this.OnShortNameChanging(value);
					this.SendPropertyChanging();
					this._ShortName = value;
					this.SendPropertyChanged("ShortName");
					this.OnShortNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="VarChar(50)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this.OnFullNameChanging(value);
					this.SendPropertyChanging();
					this._FullName = value;
					this.SendPropertyChanged("FullName");
					this.OnFullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompaneColor", DbType="Char(7)")]
		public string CompaneColor
		{
			get
			{
				return this._CompaneColor;
			}
			set
			{
				if ((this._CompaneColor != value))
				{
					this.OnCompaneColorChanging(value);
					this.SendPropertyChanging();
					this._CompaneColor = value;
					this.SendPropertyChanged("CompaneColor");
					this.OnCompaneColorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TextColor", DbType="Char(7)")]
		public string TextColor
		{
			get
			{
				return this._TextColor;
			}
			set
			{
				if ((this._TextColor != value))
				{
					this.OnTextColorChanging(value);
					this.SendPropertyChanging();
					this._TextColor = value;
					this.SendPropertyChanged("TextColor");
					this.OnTextColorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Company_CompletionActivityRelation", Storage="_CompletionActivityRelations", ThisKey="CompanyId", OtherKey="CompanyId")]
		public EntitySet<CompletionActivityRelation> CompletionActivityRelations
		{
			get
			{
				return this._CompletionActivityRelations;
			}
			set
			{
				this._CompletionActivityRelations.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CompletionActivityRelations(CompletionActivityRelation entity)
		{
			this.SendPropertyChanging();
			entity.Company = this;
		}
		
		private void detach_CompletionActivityRelations(CompletionActivityRelation entity)
		{
			this.SendPropertyChanging();
			entity.Company = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vwCompletionActivityRelations")]
	public partial class vwCompletionActivityRelation
	{
		
		private string _ComletionType;
		
		private string _CoName;
		
		private string _CoColor;
		
		private string _CoTxtColor;
		
		private string _RComment;
		
		private int _AssemblyTypeId;
		
		private int _ActivityId;
		
		public vwCompletionActivityRelation()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComletionType", DbType="NVarChar(50)")]
		public string ComletionType
		{
			get
			{
				return this._ComletionType;
			}
			set
			{
				if ((this._ComletionType != value))
				{
					this._ComletionType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoName", DbType="VarChar(50)")]
		public string CoName
		{
			get
			{
				return this._CoName;
			}
			set
			{
				if ((this._CoName != value))
				{
					this._CoName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoColor", DbType="Char(7)")]
		public string CoColor
		{
			get
			{
				return this._CoColor;
			}
			set
			{
				if ((this._CoColor != value))
				{
					this._CoColor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoTxtColor", DbType="Char(7)")]
		public string CoTxtColor
		{
			get
			{
				return this._CoTxtColor;
			}
			set
			{
				if ((this._CoTxtColor != value))
				{
					this._CoTxtColor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RComment", DbType="VarChar(50)")]
		public string RComment
		{
			get
			{
				return this._RComment;
			}
			set
			{
				if ((this._RComment != value))
				{
					this._RComment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssemblyTypeId", DbType="Int NOT NULL")]
		public int AssemblyTypeId
		{
			get
			{
				return this._AssemblyTypeId;
			}
			set
			{
				if ((this._AssemblyTypeId != value))
				{
					this._AssemblyTypeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActivityId", DbType="Int NOT NULL")]
		public int ActivityId
		{
			get
			{
				return this._ActivityId;
			}
			set
			{
				if ((this._ActivityId != value))
				{
					this._ActivityId = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
