<?xml version="1.0" encoding="utf-8"?><Database Name="DOSB" Class="CPLDataContext" Serialization="Unidirectional" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\DOSB.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DOSBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employees">
      <Column Name="EmployeeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LDAP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SegmentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Avatar" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="GivenName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SurName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PersonalMobile" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="AramcoID" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="AramcoIdExpDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="H2SExpDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="HUETExpDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GIN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Employees_WorkshopAssignments" Member="WorkshopAssignments" ThisKey="EmployeeId" OtherKey="EmployeeId" Type="WorkshopAssignments" />
      <Association Name="Employees_PressureTestLogs" Member="PressureTests" ThisKey="EmployeeId" OtherKey="ApprovedBy" Type="PressureTestLogs" />
      <Association Name="Employees_PressureTestLogs1" Member="PressureTestLogs" Storage="_PressureTests1" ThisKey="EmployeeId" OtherKey="TestBy" Type="PressureTestLogs" />
      <Association Name="Employees_Torque" Member="ApprovedTorques" AccessModifier="Internal" ThisKey="EmployeeId" OtherKey="TorqueId" Type="TorqueLogs" Cardinality="One" />
      <Association Name="Employees_Torque1" Member="PerfomedTorques" AccessModifier="Internal" ThisKey="EmployeeId" OtherKey="TorqueBy" Type="TorqueLogs" />
      <Association Name="Segments_Employees" Member="Segment" ThisKey="SegmentId" OtherKey="SegmentId" Type="Segments" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Segment" Member="Segments">
    <Type Name="Segments">
      <Column Name="SegmentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BusinessCategory" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Segments_Employees" Member="Employees" AccessModifier="Internal" ThisKey="SegmentId" OtherKey="SegmentId" Type="Employees" />
    </Type>
  </Table>
  <Table Name="dbo.WorkshopAssignment" Member="WorkshopAssignments">
    <Type Name="WorkshopAssignments">
      <Column Name="WorkshopAssignmentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmployeeId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WorkshopDailyActivityId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AssignedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Employees_WorkshopAssignments" Member="Employees" Storage="_Employee" ThisKey="EmployeeId" OtherKey="EmployeeId" Type="Employees" IsForeignKey="true" />
      <Association Name="WorkshopDailyActivities_WorkshopAssignments" Member="WorkshopDailyActivities" Storage="_WorkshopDailyActivity" ThisKey="WorkshopDailyActivityId" OtherKey="ActivityId" Type="WorkshopDailyActivities" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.WorkshopDailyActivity" Member="WorkshopDailyActivities">
    <Type Name="WorkshopDailyActivities">
      <Column Name="ActivityId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Forklift" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Torque" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PressureTest" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FinishedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CanceledAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="WorkshopDailyActivities_WorkshopAssignments" Member="WorkshopAssignments" ThisKey="ActivityId" OtherKey="WorkshopDailyActivityId" Type="WorkshopAssignments" />
    </Type>
  </Table>
  <Table Name="dbo.PressureTest" Member="PressureTestLogs">
    <Type Name="PressureTestLogs">
      <Column Name="PressureTestId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PartNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SerialNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="AssemblyType" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="StartAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FinishAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TestBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ApprovedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Defect" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Employees_PressureTestLogs" Member="Employee" ThisKey="ApprovedBy" OtherKey="EmployeeId" Type="Employees" IsForeignKey="true" />
      <Association Name="Employees_PressureTestLogs1" Member="Employees" Storage="_Employee1" ThisKey="TestBy" OtherKey="EmployeeId" Type="Employees" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Attachment" Member="Attachments">
    <Type Name="Attachments">
      <Column Name="AttachmentId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AttachableType" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="AttachableId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Torque" Member="TorqueLogs">
    <Type Name="TorqueLogs">
      <Column Name="TorqueId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PartNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SerialNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="AssemblyType" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="StartAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FinishAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TorqueBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ApprovedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Defect" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Employees_Torque" Member="EmployeeApprover" ThisKey="TorqueId" OtherKey="EmployeeId" Type="Employees" IsForeignKey="true" />
      <Association Name="Employees_Torque1" Member="EmployeePerfomer" ThisKey="TorqueBy" OtherKey="EmployeeId" Type="Employees" IsForeignKey="true" />
    </Type>
  </Table>
</Database>