//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DOSBModel", "FK_WorkshopAssignment_Employee", "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DOSB.Models.Employee), "WorkshopAssignment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DOSB.Models.WorkshopAssignment), true)]
[assembly: EdmRelationshipAttribute("DOSBModel", "FK_WorkshopAssignment_WorkshopDailyActivity", "WorkshopDailyActivity", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DOSB.Models.WorkshopDailyActivity), "WorkshopAssignment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DOSB.Models.WorkshopAssignment), true)]

#endregion

namespace DOSB.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DOSBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DOSBEntities object using the connection string found in the 'DOSBEntities' section of the application configuration file.
        /// </summary>
        public DOSBEntities() : base("name=DOSBEntities", "DOSBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DOSBEntities object.
        /// </summary>
        public DOSBEntities(string connectionString) : base(connectionString, "DOSBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DOSBEntities object.
        /// </summary>
        public DOSBEntities(EntityConnection connection) : base(connection, "DOSBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Employee> Employee
        {
            get
            {
                if ((_Employee == null))
                {
                    _Employee = base.CreateObjectSet<Employee>("Employee");
                }
                return _Employee;
            }
        }
        private ObjectSet<Employee> _Employee;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WorkshopAssignment> WorkshopAssignment
        {
            get
            {
                if ((_WorkshopAssignment == null))
                {
                    _WorkshopAssignment = base.CreateObjectSet<WorkshopAssignment>("WorkshopAssignment");
                }
                return _WorkshopAssignment;
            }
        }
        private ObjectSet<WorkshopAssignment> _WorkshopAssignment;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WorkshopDailyActivity> WorkshopDailyActivity
        {
            get
            {
                if ((_WorkshopDailyActivity == null))
                {
                    _WorkshopDailyActivity = base.CreateObjectSet<WorkshopDailyActivity>("WorkshopDailyActivity");
                }
                return _WorkshopDailyActivity;
            }
        }
        private ObjectSet<WorkshopDailyActivity> _WorkshopDailyActivity;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Employee EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmployee(Employee employee)
        {
            base.AddObject("Employee", employee);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WorkshopAssignment EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWorkshopAssignment(WorkshopAssignment workshopAssignment)
        {
            base.AddObject("WorkshopAssignment", workshopAssignment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WorkshopDailyActivity EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWorkshopDailyActivity(WorkshopDailyActivity workshopDailyActivity)
        {
            base.AddObject("WorkshopDailyActivity", workshopDailyActivity);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DOSBModel", Name="Employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Employee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="employeeId">Initial value of the EmployeeId property.</param>
        public static Employee CreateEmployee(global::System.Int32 employeeId)
        {
            Employee employee = new Employee();
            employee.EmployeeId = employeeId;
            return employee;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmployeeId
        {
            get
            {
                return _EmployeeId;
            }
            set
            {
                if (_EmployeeId != value)
                {
                    OnEmployeeIdChanging(value);
                    ReportPropertyChanging("EmployeeId");
                    _EmployeeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EmployeeId");
                    OnEmployeeIdChanged();
                }
            }
        }
        private global::System.Int32 _EmployeeId;
        partial void OnEmployeeIdChanging(global::System.Int32 value);
        partial void OnEmployeeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LDAP
        {
            get
            {
                return _LDAP;
            }
            set
            {
                OnLDAPChanging(value);
                ReportPropertyChanging("LDAP");
                _LDAP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LDAP");
                OnLDAPChanged();
            }
        }
        private global::System.String _LDAP;
        partial void OnLDAPChanging(global::System.String value);
        partial void OnLDAPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SubSegment
        {
            get
            {
                return _SubSegment;
            }
            set
            {
                OnSubSegmentChanging(value);
                ReportPropertyChanging("SubSegment");
                _SubSegment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SubSegment");
                OnSubSegmentChanged();
            }
        }
        private global::System.String _SubSegment;
        partial void OnSubSegmentChanging(global::System.String value);
        partial void OnSubSegmentChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DOSBModel", "FK_WorkshopAssignment_Employee", "WorkshopAssignment")]
        public EntityCollection<WorkshopAssignment> WorkshopAssignment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<WorkshopAssignment>("DOSBModel.FK_WorkshopAssignment_Employee", "WorkshopAssignment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<WorkshopAssignment>("DOSBModel.FK_WorkshopAssignment_Employee", "WorkshopAssignment", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DOSBModel", Name="WorkshopAssignment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WorkshopAssignment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WorkshopAssignment object.
        /// </summary>
        /// <param name="workshopAssignmentId">Initial value of the WorkshopAssignmentId property.</param>
        /// <param name="employeeId">Initial value of the EmployeeId property.</param>
        /// <param name="workshopDailyActivityId">Initial value of the WorkshopDailyActivityId property.</param>
        /// <param name="assignedAt">Initial value of the AssignedAt property.</param>
        public static WorkshopAssignment CreateWorkshopAssignment(global::System.Int32 workshopAssignmentId, global::System.Int32 employeeId, global::System.Int32 workshopDailyActivityId, global::System.DateTime assignedAt)
        {
            WorkshopAssignment workshopAssignment = new WorkshopAssignment();
            workshopAssignment.WorkshopAssignmentId = workshopAssignmentId;
            workshopAssignment.EmployeeId = employeeId;
            workshopAssignment.WorkshopDailyActivityId = workshopDailyActivityId;
            workshopAssignment.AssignedAt = assignedAt;
            return workshopAssignment;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WorkshopAssignmentId
        {
            get
            {
                return _WorkshopAssignmentId;
            }
            set
            {
                if (_WorkshopAssignmentId != value)
                {
                    OnWorkshopAssignmentIdChanging(value);
                    ReportPropertyChanging("WorkshopAssignmentId");
                    _WorkshopAssignmentId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("WorkshopAssignmentId");
                    OnWorkshopAssignmentIdChanged();
                }
            }
        }
        private global::System.Int32 _WorkshopAssignmentId;
        partial void OnWorkshopAssignmentIdChanging(global::System.Int32 value);
        partial void OnWorkshopAssignmentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmployeeId
        {
            get
            {
                return _EmployeeId;
            }
            set
            {
                if (_EmployeeId != value)
                {
                    OnEmployeeIdChanging(value);
                    ReportPropertyChanging("EmployeeId");
                    _EmployeeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EmployeeId");
                    OnEmployeeIdChanged();
                }
            }
        }
        private global::System.Int32 _EmployeeId;
        partial void OnEmployeeIdChanging(global::System.Int32 value);
        partial void OnEmployeeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WorkshopDailyActivityId
        {
            get
            {
                return _WorkshopDailyActivityId;
            }
            set
            {
                if (_WorkshopDailyActivityId != value)
                {
                    OnWorkshopDailyActivityIdChanging(value);
                    ReportPropertyChanging("WorkshopDailyActivityId");
                    _WorkshopDailyActivityId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("WorkshopDailyActivityId");
                    OnWorkshopDailyActivityIdChanged();
                }
            }
        }
        private global::System.Int32 _WorkshopDailyActivityId;
        partial void OnWorkshopDailyActivityIdChanging(global::System.Int32 value);
        partial void OnWorkshopDailyActivityIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AssignedAt
        {
            get
            {
                return _AssignedAt;
            }
            set
            {
                OnAssignedAtChanging(value);
                ReportPropertyChanging("AssignedAt");
                _AssignedAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AssignedAt");
                OnAssignedAtChanged();
            }
        }
        private global::System.DateTime _AssignedAt;
        partial void OnAssignedAtChanging(global::System.DateTime value);
        partial void OnAssignedAtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndedAt
        {
            get
            {
                return _EndedAt;
            }
            set
            {
                OnEndedAtChanging(value);
                ReportPropertyChanging("EndedAt");
                _EndedAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndedAt");
                OnEndedAtChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndedAt;
        partial void OnEndedAtChanging(Nullable<global::System.DateTime> value);
        partial void OnEndedAtChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DOSBModel", "FK_WorkshopAssignment_Employee", "Employee")]
        public Employee Employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DOSBModel.FK_WorkshopAssignment_Employee", "Employee").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DOSBModel.FK_WorkshopAssignment_Employee", "Employee").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> EmployeeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DOSBModel.FK_WorkshopAssignment_Employee", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("DOSBModel.FK_WorkshopAssignment_Employee", "Employee", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DOSBModel", "FK_WorkshopAssignment_WorkshopDailyActivity", "WorkshopDailyActivity")]
        public WorkshopDailyActivity WorkshopDailyActivity
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WorkshopDailyActivity>("DOSBModel.FK_WorkshopAssignment_WorkshopDailyActivity", "WorkshopDailyActivity").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WorkshopDailyActivity>("DOSBModel.FK_WorkshopAssignment_WorkshopDailyActivity", "WorkshopDailyActivity").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<WorkshopDailyActivity> WorkshopDailyActivityReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WorkshopDailyActivity>("DOSBModel.FK_WorkshopAssignment_WorkshopDailyActivity", "WorkshopDailyActivity");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<WorkshopDailyActivity>("DOSBModel.FK_WorkshopAssignment_WorkshopDailyActivity", "WorkshopDailyActivity", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DOSBModel", Name="WorkshopDailyActivity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WorkshopDailyActivity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WorkshopDailyActivity object.
        /// </summary>
        /// <param name="activityId">Initial value of the ActivityId property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="forklift">Initial value of the Forklift property.</param>
        /// <param name="torque">Initial value of the Torque property.</param>
        /// <param name="pressureTest">Initial value of the PressureTest property.</param>
        /// <param name="createdAt">Initial value of the CreatedAt property.</param>
        public static WorkshopDailyActivity CreateWorkshopDailyActivity(global::System.Int32 activityId, global::System.String description, global::System.Int32 forklift, global::System.Int32 torque, global::System.Int32 pressureTest, global::System.DateTime createdAt)
        {
            WorkshopDailyActivity workshopDailyActivity = new WorkshopDailyActivity();
            workshopDailyActivity.ActivityId = activityId;
            workshopDailyActivity.Description = description;
            workshopDailyActivity.Forklift = forklift;
            workshopDailyActivity.Torque = torque;
            workshopDailyActivity.PressureTest = pressureTest;
            workshopDailyActivity.CreatedAt = createdAt;
            return workshopDailyActivity;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ActivityId
        {
            get
            {
                return _ActivityId;
            }
            set
            {
                if (_ActivityId != value)
                {
                    OnActivityIdChanging(value);
                    ReportPropertyChanging("ActivityId");
                    _ActivityId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ActivityId");
                    OnActivityIdChanged();
                }
            }
        }
        private global::System.Int32 _ActivityId;
        partial void OnActivityIdChanging(global::System.Int32 value);
        partial void OnActivityIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Forklift
        {
            get
            {
                return _Forklift;
            }
            set
            {
                OnForkliftChanging(value);
                ReportPropertyChanging("Forklift");
                _Forklift = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Forklift");
                OnForkliftChanged();
            }
        }
        private global::System.Int32 _Forklift;
        partial void OnForkliftChanging(global::System.Int32 value);
        partial void OnForkliftChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Torque
        {
            get
            {
                return _Torque;
            }
            set
            {
                OnTorqueChanging(value);
                ReportPropertyChanging("Torque");
                _Torque = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Torque");
                OnTorqueChanged();
            }
        }
        private global::System.Int32 _Torque;
        partial void OnTorqueChanging(global::System.Int32 value);
        partial void OnTorqueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PressureTest
        {
            get
            {
                return _PressureTest;
            }
            set
            {
                OnPressureTestChanging(value);
                ReportPropertyChanging("PressureTest");
                _PressureTest = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PressureTest");
                OnPressureTestChanged();
            }
        }
        private global::System.Int32 _PressureTest;
        partial void OnPressureTestChanging(global::System.Int32 value);
        partial void OnPressureTestChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedAt
        {
            get
            {
                return _CreatedAt;
            }
            set
            {
                OnCreatedAtChanging(value);
                ReportPropertyChanging("CreatedAt");
                _CreatedAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedAt");
                OnCreatedAtChanged();
            }
        }
        private global::System.DateTime _CreatedAt;
        partial void OnCreatedAtChanging(global::System.DateTime value);
        partial void OnCreatedAtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FinishedAt
        {
            get
            {
                return _FinishedAt;
            }
            set
            {
                OnFinishedAtChanging(value);
                ReportPropertyChanging("FinishedAt");
                _FinishedAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FinishedAt");
                OnFinishedAtChanged();
            }
        }
        private Nullable<global::System.DateTime> _FinishedAt;
        partial void OnFinishedAtChanging(Nullable<global::System.DateTime> value);
        partial void OnFinishedAtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CanceledAt
        {
            get
            {
                return _CanceledAt;
            }
            set
            {
                OnCanceledAtChanging(value);
                ReportPropertyChanging("CanceledAt");
                _CanceledAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CanceledAt");
                OnCanceledAtChanged();
            }
        }
        private Nullable<global::System.DateTime> _CanceledAt;
        partial void OnCanceledAtChanging(Nullable<global::System.DateTime> value);
        partial void OnCanceledAtChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DOSBModel", "FK_WorkshopAssignment_WorkshopDailyActivity", "WorkshopAssignment")]
        public EntityCollection<WorkshopAssignment> WorkshopAssignment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<WorkshopAssignment>("DOSBModel.FK_WorkshopAssignment_WorkshopDailyActivity", "WorkshopAssignment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<WorkshopAssignment>("DOSBModel.FK_WorkshopAssignment_WorkshopDailyActivity", "WorkshopAssignment", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
