//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DOSBModel", "FK_Employee_Segment", "Segment", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DOSB.Models.Segment), "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DOSB.Models.Employee), true)]
[assembly: EdmRelationshipAttribute("DOSBModel", "FK_Torque_Employee", "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DOSB.Models.Employee), "Torque", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DOSB.Models.Torque), true)]
[assembly: EdmRelationshipAttribute("DOSBModel", "FK_WorkshopAssignment_Employee", "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DOSB.Models.Employee), "WorkshopAssignment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DOSB.Models.WorkshopAssignment), true)]
[assembly: EdmRelationshipAttribute("DOSBModel", "FK_Segment_Parent", "Segment", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DOSB.Models.Segment), "Segment1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DOSB.Models.Segment), true)]
[assembly: EdmRelationshipAttribute("DOSBModel", "FK_WorkshopAssignment_WorkshopDailyActivity", "WorkshopDailyActivity", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DOSB.Models.WorkshopDailyActivity), "WorkshopAssignment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DOSB.Models.WorkshopAssignment), true)]
[assembly: EdmRelationshipAttribute("DOSBModel", "FK_PressureTest_Employee", "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DOSB.Models.Employee), "PressureTest", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DOSB.Models.PressureTest), true)]
[assembly: EdmRelationshipAttribute("DOSBModel", "FK_PressureTest_Approver", "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DOSB.Models.Employee), "PressureTest", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DOSB.Models.PressureTest), true)]
[assembly: EdmRelationshipAttribute("DOSBModel", "FK_Torque_Approver", "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DOSB.Models.Employee), "Torque", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DOSB.Models.Torque), true)]

#endregion

namespace DOSB.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DOSBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DOSBEntities object using the connection string found in the 'DOSBEntities' section of the application configuration file.
        /// </summary>
        public DOSBEntities() : base("name=DOSBEntities", "DOSBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DOSBEntities object.
        /// </summary>
        public DOSBEntities(string connectionString) : base(connectionString, "DOSBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DOSBEntities object.
        /// </summary>
        public DOSBEntities(EntityConnection connection) : base(connection, "DOSBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Employee> Employee
        {
            get
            {
                if ((_Employee == null))
                {
                    _Employee = base.CreateObjectSet<Employee>("Employee");
                }
                return _Employee;
            }
        }
        private ObjectSet<Employee> _Employee;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Segment> Segment
        {
            get
            {
                if ((_Segment == null))
                {
                    _Segment = base.CreateObjectSet<Segment>("Segment");
                }
                return _Segment;
            }
        }
        private ObjectSet<Segment> _Segment;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Torque> Torque
        {
            get
            {
                if ((_Torque == null))
                {
                    _Torque = base.CreateObjectSet<Torque>("Torque");
                }
                return _Torque;
            }
        }
        private ObjectSet<Torque> _Torque;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WorkshopAssignment> WorkshopAssignment
        {
            get
            {
                if ((_WorkshopAssignment == null))
                {
                    _WorkshopAssignment = base.CreateObjectSet<WorkshopAssignment>("WorkshopAssignment");
                }
                return _WorkshopAssignment;
            }
        }
        private ObjectSet<WorkshopAssignment> _WorkshopAssignment;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WorkshopDailyActivity> WorkshopDailyActivity
        {
            get
            {
                if ((_WorkshopDailyActivity == null))
                {
                    _WorkshopDailyActivity = base.CreateObjectSet<WorkshopDailyActivity>("WorkshopDailyActivity");
                }
                return _WorkshopDailyActivity;
            }
        }
        private ObjectSet<WorkshopDailyActivity> _WorkshopDailyActivity;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Attachment> Attachment
        {
            get
            {
                if ((_Attachment == null))
                {
                    _Attachment = base.CreateObjectSet<Attachment>("Attachment");
                }
                return _Attachment;
            }
        }
        private ObjectSet<Attachment> _Attachment;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PressureTest> PressureTest
        {
            get
            {
                if ((_PressureTest == null))
                {
                    _PressureTest = base.CreateObjectSet<PressureTest>("PressureTest");
                }
                return _PressureTest;
            }
        }
        private ObjectSet<PressureTest> _PressureTest;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Employee EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmployee(Employee employee)
        {
            base.AddObject("Employee", employee);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Segment EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSegment(Segment segment)
        {
            base.AddObject("Segment", segment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Torque EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTorque(Torque torque)
        {
            base.AddObject("Torque", torque);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WorkshopAssignment EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWorkshopAssignment(WorkshopAssignment workshopAssignment)
        {
            base.AddObject("WorkshopAssignment", workshopAssignment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WorkshopDailyActivity EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWorkshopDailyActivity(WorkshopDailyActivity workshopDailyActivity)
        {
            base.AddObject("WorkshopDailyActivity", workshopDailyActivity);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Attachment EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAttachment(Attachment attachment)
        {
            base.AddObject("Attachment", attachment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PressureTest EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPressureTest(PressureTest pressureTest)
        {
            base.AddObject("PressureTest", pressureTest);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DOSBModel", Name="Attachment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Attachment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Attachment object.
        /// </summary>
        /// <param name="attachmentId">Initial value of the AttachmentId property.</param>
        public static Attachment CreateAttachment(global::System.Int32 attachmentId)
        {
            Attachment attachment = new Attachment();
            attachment.AttachmentId = attachmentId;
            return attachment;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AttachmentId
        {
            get
            {
                return _AttachmentId;
            }
            set
            {
                if (_AttachmentId != value)
                {
                    OnAttachmentIdChanging(value);
                    ReportPropertyChanging("AttachmentId");
                    _AttachmentId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AttachmentId");
                    OnAttachmentIdChanged();
                }
            }
        }
        private global::System.Int32 _AttachmentId;
        partial void OnAttachmentIdChanging(global::System.Int32 value);
        partial void OnAttachmentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AttachableType
        {
            get
            {
                return _AttachableType;
            }
            set
            {
                OnAttachableTypeChanging(value);
                ReportPropertyChanging("AttachableType");
                _AttachableType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AttachableType");
                OnAttachableTypeChanged();
            }
        }
        private global::System.String _AttachableType;
        partial void OnAttachableTypeChanging(global::System.String value);
        partial void OnAttachableTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AttachableId
        {
            get
            {
                return _AttachableId;
            }
            set
            {
                OnAttachableIdChanging(value);
                ReportPropertyChanging("AttachableId");
                _AttachableId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AttachableId");
                OnAttachableIdChanged();
            }
        }
        private Nullable<global::System.Int32> _AttachableId;
        partial void OnAttachableIdChanging(Nullable<global::System.Int32> value);
        partial void OnAttachableIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Guid
        {
            get
            {
                return _Guid;
            }
            set
            {
                OnGuidChanging(value);
                ReportPropertyChanging("Guid");
                _Guid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Guid");
                OnGuidChanged();
            }
        }
        private global::System.String _Guid;
        partial void OnGuidChanging(global::System.String value);
        partial void OnGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FileName
        {
            get
            {
                return _FileName;
            }
            set
            {
                OnFileNameChanging(value);
                ReportPropertyChanging("FileName");
                _FileName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FileName");
                OnFileNameChanged();
            }
        }
        private global::System.String _FileName;
        partial void OnFileNameChanging(global::System.String value);
        partial void OnFileNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DOSBModel", Name="Employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Employee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="employeeId">Initial value of the EmployeeId property.</param>
        public static Employee CreateEmployee(global::System.Int32 employeeId)
        {
            Employee employee = new Employee();
            employee.EmployeeId = employeeId;
            return employee;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmployeeId
        {
            get
            {
                return _EmployeeId;
            }
            set
            {
                if (_EmployeeId != value)
                {
                    OnEmployeeIdChanging(value);
                    ReportPropertyChanging("EmployeeId");
                    _EmployeeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EmployeeId");
                    OnEmployeeIdChanged();
                }
            }
        }
        private global::System.Int32 _EmployeeId;
        partial void OnEmployeeIdChanging(global::System.Int32 value);
        partial void OnEmployeeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LDAP
        {
            get
            {
                return _LDAP;
            }
            set
            {
                OnLDAPChanging(value);
                ReportPropertyChanging("LDAP");
                _LDAP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LDAP");
                OnLDAPChanged();
            }
        }
        private global::System.String _LDAP;
        partial void OnLDAPChanging(global::System.String value);
        partial void OnLDAPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SegmentId
        {
            get
            {
                return _SegmentId;
            }
            set
            {
                OnSegmentIdChanging(value);
                ReportPropertyChanging("SegmentId");
                _SegmentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SegmentId");
                OnSegmentIdChanged();
            }
        }
        private Nullable<global::System.Int32> _SegmentId;
        partial void OnSegmentIdChanging(Nullable<global::System.Int32> value);
        partial void OnSegmentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Avatar
        {
            get
            {
                return StructuralObject.GetValidValue(_Avatar);
            }
            set
            {
                OnAvatarChanging(value);
                ReportPropertyChanging("Avatar");
                _Avatar = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Avatar");
                OnAvatarChanged();
            }
        }
        private global::System.Byte[] _Avatar;
        partial void OnAvatarChanging(global::System.Byte[] value);
        partial void OnAvatarChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GivenName
        {
            get
            {
                return _GivenName;
            }
            set
            {
                OnGivenNameChanging(value);
                ReportPropertyChanging("GivenName");
                _GivenName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GivenName");
                OnGivenNameChanged();
            }
        }
        private global::System.String _GivenName;
        partial void OnGivenNameChanging(global::System.String value);
        partial void OnGivenNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SurName
        {
            get
            {
                return _SurName;
            }
            set
            {
                OnSurNameChanging(value);
                ReportPropertyChanging("SurName");
                _SurName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SurName");
                OnSurNameChanged();
            }
        }
        private global::System.String _SurName;
        partial void OnSurNameChanging(global::System.String value);
        partial void OnSurNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mobile
        {
            get
            {
                return _Mobile;
            }
            set
            {
                OnMobileChanging(value);
                ReportPropertyChanging("Mobile");
                _Mobile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mobile");
                OnMobileChanged();
            }
        }
        private global::System.String _Mobile;
        partial void OnMobileChanging(global::System.String value);
        partial void OnMobileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PersonalMobile
        {
            get
            {
                return _PersonalMobile;
            }
            set
            {
                OnPersonalMobileChanging(value);
                ReportPropertyChanging("PersonalMobile");
                _PersonalMobile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PersonalMobile");
                OnPersonalMobileChanged();
            }
        }
        private global::System.String _PersonalMobile;
        partial void OnPersonalMobileChanging(global::System.String value);
        partial void OnPersonalMobileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AramcoID
        {
            get
            {
                return _AramcoID;
            }
            set
            {
                OnAramcoIDChanging(value);
                ReportPropertyChanging("AramcoID");
                _AramcoID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AramcoID");
                OnAramcoIDChanged();
            }
        }
        private global::System.String _AramcoID;
        partial void OnAramcoIDChanging(global::System.String value);
        partial void OnAramcoIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> AramcoIdExpDate
        {
            get
            {
                return _AramcoIdExpDate;
            }
            set
            {
                OnAramcoIdExpDateChanging(value);
                ReportPropertyChanging("AramcoIdExpDate");
                _AramcoIdExpDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AramcoIdExpDate");
                OnAramcoIdExpDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _AramcoIdExpDate;
        partial void OnAramcoIdExpDateChanging(Nullable<global::System.DateTime> value);
        partial void OnAramcoIdExpDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> H2SExpDate
        {
            get
            {
                return _H2SExpDate;
            }
            set
            {
                OnH2SExpDateChanging(value);
                ReportPropertyChanging("H2SExpDate");
                _H2SExpDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("H2SExpDate");
                OnH2SExpDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _H2SExpDate;
        partial void OnH2SExpDateChanging(Nullable<global::System.DateTime> value);
        partial void OnH2SExpDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> HUETExpDate
        {
            get
            {
                return _HUETExpDate;
            }
            set
            {
                OnHUETExpDateChanging(value);
                ReportPropertyChanging("HUETExpDate");
                _HUETExpDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HUETExpDate");
                OnHUETExpDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _HUETExpDate;
        partial void OnHUETExpDateChanging(Nullable<global::System.DateTime> value);
        partial void OnHUETExpDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GIN
        {
            get
            {
                return _GIN;
            }
            set
            {
                OnGINChanging(value);
                ReportPropertyChanging("GIN");
                _GIN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GIN");
                OnGINChanged();
            }
        }
        private global::System.String _GIN;
        partial void OnGINChanging(global::System.String value);
        partial void OnGINChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DOSBModel", "FK_Employee_Segment", "Segment")]
        public Segment Segment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Segment>("DOSBModel.FK_Employee_Segment", "Segment").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Segment>("DOSBModel.FK_Employee_Segment", "Segment").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Segment> SegmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Segment>("DOSBModel.FK_Employee_Segment", "Segment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Segment>("DOSBModel.FK_Employee_Segment", "Segment", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DOSBModel", "FK_Torque_Employee", "Torque")]
        public EntityCollection<Torque> Torque
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Torque>("DOSBModel.FK_Torque_Employee", "Torque");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Torque>("DOSBModel.FK_Torque_Employee", "Torque", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DOSBModel", "FK_WorkshopAssignment_Employee", "WorkshopAssignment")]
        public EntityCollection<WorkshopAssignment> WorkshopAssignment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<WorkshopAssignment>("DOSBModel.FK_WorkshopAssignment_Employee", "WorkshopAssignment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<WorkshopAssignment>("DOSBModel.FK_WorkshopAssignment_Employee", "WorkshopAssignment", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DOSBModel", "FK_PressureTest_Employee", "PressureTest")]
        public EntityCollection<PressureTest> PressureTest
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PressureTest>("DOSBModel.FK_PressureTest_Employee", "PressureTest");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PressureTest>("DOSBModel.FK_PressureTest_Employee", "PressureTest", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DOSBModel", "FK_PressureTest_Approver", "PressureTest")]
        public EntityCollection<PressureTest> PressureTest_1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PressureTest>("DOSBModel.FK_PressureTest_Approver", "PressureTest");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PressureTest>("DOSBModel.FK_PressureTest_Approver", "PressureTest", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DOSBModel", "FK_Torque_Approver", "Torque")]
        public Torque Torque_1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Torque>("DOSBModel.FK_Torque_Approver", "Torque").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Torque>("DOSBModel.FK_Torque_Approver", "Torque").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Torque> Torque_1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Torque>("DOSBModel.FK_Torque_Approver", "Torque");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Torque>("DOSBModel.FK_Torque_Approver", "Torque", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DOSBModel", Name="PressureTest")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PressureTest : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PressureTest object.
        /// </summary>
        /// <param name="pressureTestId">Initial value of the PressureTestId property.</param>
        public static PressureTest CreatePressureTest(global::System.Int32 pressureTestId)
        {
            PressureTest pressureTest = new PressureTest();
            pressureTest.PressureTestId = pressureTestId;
            return pressureTest;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PressureTestId
        {
            get
            {
                return _PressureTestId;
            }
            set
            {
                if (_PressureTestId != value)
                {
                    OnPressureTestIdChanging(value);
                    ReportPropertyChanging("PressureTestId");
                    _PressureTestId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PressureTestId");
                    OnPressureTestIdChanged();
                }
            }
        }
        private global::System.Int32 _PressureTestId;
        partial void OnPressureTestIdChanging(global::System.Int32 value);
        partial void OnPressureTestIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PartNumber
        {
            get
            {
                return _PartNumber;
            }
            set
            {
                OnPartNumberChanging(value);
                ReportPropertyChanging("PartNumber");
                _PartNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PartNumber");
                OnPartNumberChanged();
            }
        }
        private global::System.String _PartNumber;
        partial void OnPartNumberChanging(global::System.String value);
        partial void OnPartNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SerialNumber
        {
            get
            {
                return _SerialNumber;
            }
            set
            {
                OnSerialNumberChanging(value);
                ReportPropertyChanging("SerialNumber");
                _SerialNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SerialNumber");
                OnSerialNumberChanged();
            }
        }
        private global::System.String _SerialNumber;
        partial void OnSerialNumberChanging(global::System.String value);
        partial void OnSerialNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TestBy
        {
            get
            {
                return _TestBy;
            }
            set
            {
                OnTestByChanging(value);
                ReportPropertyChanging("TestBy");
                _TestBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TestBy");
                OnTestByChanged();
            }
        }
        private Nullable<global::System.Int32> _TestBy;
        partial void OnTestByChanging(Nullable<global::System.Int32> value);
        partial void OnTestByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartAt
        {
            get
            {
                return _StartAt;
            }
            set
            {
                OnStartAtChanging(value);
                ReportPropertyChanging("StartAt");
                _StartAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartAt");
                OnStartAtChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartAt;
        partial void OnStartAtChanging(Nullable<global::System.DateTime> value);
        partial void OnStartAtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FinishAt
        {
            get
            {
                return _FinishAt;
            }
            set
            {
                OnFinishAtChanging(value);
                ReportPropertyChanging("FinishAt");
                _FinishAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FinishAt");
                OnFinishAtChanged();
            }
        }
        private Nullable<global::System.DateTime> _FinishAt;
        partial void OnFinishAtChanging(Nullable<global::System.DateTime> value);
        partial void OnFinishAtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Defect
        {
            get
            {
                return _Defect;
            }
            set
            {
                OnDefectChanging(value);
                ReportPropertyChanging("Defect");
                _Defect = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Defect");
                OnDefectChanged();
            }
        }
        private Nullable<global::System.Int32> _Defect;
        partial void OnDefectChanging(Nullable<global::System.Int32> value);
        partial void OnDefectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AssemblyType
        {
            get
            {
                return _AssemblyType;
            }
            set
            {
                OnAssemblyTypeChanging(value);
                ReportPropertyChanging("AssemblyType");
                _AssemblyType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AssemblyType");
                OnAssemblyTypeChanged();
            }
        }
        private global::System.String _AssemblyType;
        partial void OnAssemblyTypeChanging(global::System.String value);
        partial void OnAssemblyTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ApprovedBy
        {
            get
            {
                return _ApprovedBy;
            }
            set
            {
                OnApprovedByChanging(value);
                ReportPropertyChanging("ApprovedBy");
                _ApprovedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ApprovedBy");
                OnApprovedByChanged();
            }
        }
        private Nullable<global::System.Int32> _ApprovedBy;
        partial void OnApprovedByChanging(Nullable<global::System.Int32> value);
        partial void OnApprovedByChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DOSBModel", "FK_PressureTest_Employee", "Employee")]
        public Employee Employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DOSBModel.FK_PressureTest_Employee", "Employee").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DOSBModel.FK_PressureTest_Employee", "Employee").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> EmployeeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DOSBModel.FK_PressureTest_Employee", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("DOSBModel.FK_PressureTest_Employee", "Employee", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DOSBModel", "FK_PressureTest_Approver", "Employee")]
        public Employee Approver
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DOSBModel.FK_PressureTest_Approver", "Employee").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DOSBModel.FK_PressureTest_Approver", "Employee").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> ApproverReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DOSBModel.FK_PressureTest_Approver", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("DOSBModel.FK_PressureTest_Approver", "Employee", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DOSBModel", Name="Segment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Segment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Segment object.
        /// </summary>
        /// <param name="segmentId">Initial value of the SegmentId property.</param>
        /// <param name="parentId">Initial value of the ParentId property.</param>
        public static Segment CreateSegment(global::System.Int32 segmentId, global::System.Int32 parentId)
        {
            Segment segment = new Segment();
            segment.SegmentId = segmentId;
            segment.ParentId = parentId;
            return segment;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SegmentId
        {
            get
            {
                return _SegmentId;
            }
            set
            {
                if (_SegmentId != value)
                {
                    OnSegmentIdChanging(value);
                    ReportPropertyChanging("SegmentId");
                    _SegmentId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SegmentId");
                    OnSegmentIdChanged();
                }
            }
        }
        private global::System.Int32 _SegmentId;
        partial void OnSegmentIdChanging(global::System.Int32 value);
        partial void OnSegmentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FullName
        {
            get
            {
                return _FullName;
            }
            set
            {
                OnFullNameChanging(value);
                ReportPropertyChanging("FullName");
                _FullName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FullName");
                OnFullNameChanged();
            }
        }
        private global::System.String _FullName;
        partial void OnFullNameChanging(global::System.String value);
        partial void OnFullNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ParentId
        {
            get
            {
                return _ParentId;
            }
            set
            {
                OnParentIdChanging(value);
                ReportPropertyChanging("ParentId");
                _ParentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentId");
                OnParentIdChanged();
            }
        }
        private global::System.Int32 _ParentId;
        partial void OnParentIdChanging(global::System.Int32 value);
        partial void OnParentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BusinessCategory
        {
            get
            {
                return _BusinessCategory;
            }
            set
            {
                OnBusinessCategoryChanging(value);
                ReportPropertyChanging("BusinessCategory");
                _BusinessCategory = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BusinessCategory");
                OnBusinessCategoryChanged();
            }
        }
        private global::System.String _BusinessCategory;
        partial void OnBusinessCategoryChanging(global::System.String value);
        partial void OnBusinessCategoryChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DOSBModel", "FK_Employee_Segment", "Employee")]
        public EntityCollection<Employee> Employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Employee>("DOSBModel.FK_Employee_Segment", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Employee>("DOSBModel.FK_Employee_Segment", "Employee", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DOSBModel", "FK_Segment_Parent", "Segment1")]
        public EntityCollection<Segment> Segment1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Segment>("DOSBModel.FK_Segment_Parent", "Segment1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Segment>("DOSBModel.FK_Segment_Parent", "Segment1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DOSBModel", "FK_Segment_Parent", "Segment")]
        public Segment Segment2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Segment>("DOSBModel.FK_Segment_Parent", "Segment").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Segment>("DOSBModel.FK_Segment_Parent", "Segment").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Segment> Segment2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Segment>("DOSBModel.FK_Segment_Parent", "Segment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Segment>("DOSBModel.FK_Segment_Parent", "Segment", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DOSBModel", Name="Torque")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Torque : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Torque object.
        /// </summary>
        /// <param name="torqueId">Initial value of the TorqueId property.</param>
        /// <param name="serialNumber">Initial value of the SerialNumber property.</param>
        public static Torque CreateTorque(global::System.Int32 torqueId, global::System.String serialNumber)
        {
            Torque torque = new Torque();
            torque.TorqueId = torqueId;
            torque.SerialNumber = serialNumber;
            return torque;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TorqueId
        {
            get
            {
                return _TorqueId;
            }
            set
            {
                if (_TorqueId != value)
                {
                    OnTorqueIdChanging(value);
                    ReportPropertyChanging("TorqueId");
                    _TorqueId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TorqueId");
                    OnTorqueIdChanged();
                }
            }
        }
        private global::System.Int32 _TorqueId;
        partial void OnTorqueIdChanging(global::System.Int32 value);
        partial void OnTorqueIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PartNumber
        {
            get
            {
                return _PartNumber;
            }
            set
            {
                OnPartNumberChanging(value);
                ReportPropertyChanging("PartNumber");
                _PartNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PartNumber");
                OnPartNumberChanged();
            }
        }
        private global::System.String _PartNumber;
        partial void OnPartNumberChanging(global::System.String value);
        partial void OnPartNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SerialNumber
        {
            get
            {
                return _SerialNumber;
            }
            set
            {
                OnSerialNumberChanging(value);
                ReportPropertyChanging("SerialNumber");
                _SerialNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SerialNumber");
                OnSerialNumberChanged();
            }
        }
        private global::System.String _SerialNumber;
        partial void OnSerialNumberChanging(global::System.String value);
        partial void OnSerialNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TorqueBy
        {
            get
            {
                return _TorqueBy;
            }
            set
            {
                OnTorqueByChanging(value);
                ReportPropertyChanging("TorqueBy");
                _TorqueBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TorqueBy");
                OnTorqueByChanged();
            }
        }
        private Nullable<global::System.Int32> _TorqueBy;
        partial void OnTorqueByChanging(Nullable<global::System.Int32> value);
        partial void OnTorqueByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartAt
        {
            get
            {
                return _StartAt;
            }
            set
            {
                OnStartAtChanging(value);
                ReportPropertyChanging("StartAt");
                _StartAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartAt");
                OnStartAtChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartAt;
        partial void OnStartAtChanging(Nullable<global::System.DateTime> value);
        partial void OnStartAtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FinishAt
        {
            get
            {
                return _FinishAt;
            }
            set
            {
                OnFinishAtChanging(value);
                ReportPropertyChanging("FinishAt");
                _FinishAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FinishAt");
                OnFinishAtChanged();
            }
        }
        private Nullable<global::System.DateTime> _FinishAt;
        partial void OnFinishAtChanging(Nullable<global::System.DateTime> value);
        partial void OnFinishAtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Defect
        {
            get
            {
                return _Defect;
            }
            set
            {
                OnDefectChanging(value);
                ReportPropertyChanging("Defect");
                _Defect = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Defect");
                OnDefectChanged();
            }
        }
        private Nullable<global::System.Int32> _Defect;
        partial void OnDefectChanging(Nullable<global::System.Int32> value);
        partial void OnDefectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AssemblyType
        {
            get
            {
                return _AssemblyType;
            }
            set
            {
                OnAssemblyTypeChanging(value);
                ReportPropertyChanging("AssemblyType");
                _AssemblyType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AssemblyType");
                OnAssemblyTypeChanged();
            }
        }
        private global::System.String _AssemblyType;
        partial void OnAssemblyTypeChanging(global::System.String value);
        partial void OnAssemblyTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ApprovedBy
        {
            get
            {
                return _ApprovedBy;
            }
            set
            {
                OnApprovedByChanging(value);
                ReportPropertyChanging("ApprovedBy");
                _ApprovedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ApprovedBy");
                OnApprovedByChanged();
            }
        }
        private Nullable<global::System.Int32> _ApprovedBy;
        partial void OnApprovedByChanging(Nullable<global::System.Int32> value);
        partial void OnApprovedByChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DOSBModel", "FK_Torque_Employee", "Employee")]
        public Employee Employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DOSBModel.FK_Torque_Employee", "Employee").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DOSBModel.FK_Torque_Employee", "Employee").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> EmployeeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DOSBModel.FK_Torque_Employee", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("DOSBModel.FK_Torque_Employee", "Employee", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DOSBModel", "FK_Torque_Approver", "Employee")]
        public Employee Approver
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DOSBModel.FK_Torque_Approver", "Employee").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DOSBModel.FK_Torque_Approver", "Employee").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> ApproverReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DOSBModel.FK_Torque_Approver", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("DOSBModel.FK_Torque_Approver", "Employee", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DOSBModel", Name="WorkshopAssignment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WorkshopAssignment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WorkshopAssignment object.
        /// </summary>
        /// <param name="workshopAssignmentId">Initial value of the WorkshopAssignmentId property.</param>
        /// <param name="employeeId">Initial value of the EmployeeId property.</param>
        /// <param name="workshopDailyActivityId">Initial value of the WorkshopDailyActivityId property.</param>
        /// <param name="assignedAt">Initial value of the AssignedAt property.</param>
        public static WorkshopAssignment CreateWorkshopAssignment(global::System.Int32 workshopAssignmentId, global::System.Int32 employeeId, global::System.Int32 workshopDailyActivityId, global::System.DateTime assignedAt)
        {
            WorkshopAssignment workshopAssignment = new WorkshopAssignment();
            workshopAssignment.WorkshopAssignmentId = workshopAssignmentId;
            workshopAssignment.EmployeeId = employeeId;
            workshopAssignment.WorkshopDailyActivityId = workshopDailyActivityId;
            workshopAssignment.AssignedAt = assignedAt;
            return workshopAssignment;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WorkshopAssignmentId
        {
            get
            {
                return _WorkshopAssignmentId;
            }
            set
            {
                if (_WorkshopAssignmentId != value)
                {
                    OnWorkshopAssignmentIdChanging(value);
                    ReportPropertyChanging("WorkshopAssignmentId");
                    _WorkshopAssignmentId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("WorkshopAssignmentId");
                    OnWorkshopAssignmentIdChanged();
                }
            }
        }
        private global::System.Int32 _WorkshopAssignmentId;
        partial void OnWorkshopAssignmentIdChanging(global::System.Int32 value);
        partial void OnWorkshopAssignmentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmployeeId
        {
            get
            {
                return _EmployeeId;
            }
            set
            {
                if (_EmployeeId != value)
                {
                    OnEmployeeIdChanging(value);
                    ReportPropertyChanging("EmployeeId");
                    _EmployeeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EmployeeId");
                    OnEmployeeIdChanged();
                }
            }
        }
        private global::System.Int32 _EmployeeId;
        partial void OnEmployeeIdChanging(global::System.Int32 value);
        partial void OnEmployeeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WorkshopDailyActivityId
        {
            get
            {
                return _WorkshopDailyActivityId;
            }
            set
            {
                if (_WorkshopDailyActivityId != value)
                {
                    OnWorkshopDailyActivityIdChanging(value);
                    ReportPropertyChanging("WorkshopDailyActivityId");
                    _WorkshopDailyActivityId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("WorkshopDailyActivityId");
                    OnWorkshopDailyActivityIdChanged();
                }
            }
        }
        private global::System.Int32 _WorkshopDailyActivityId;
        partial void OnWorkshopDailyActivityIdChanging(global::System.Int32 value);
        partial void OnWorkshopDailyActivityIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AssignedAt
        {
            get
            {
                return _AssignedAt;
            }
            set
            {
                OnAssignedAtChanging(value);
                ReportPropertyChanging("AssignedAt");
                _AssignedAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AssignedAt");
                OnAssignedAtChanged();
            }
        }
        private global::System.DateTime _AssignedAt;
        partial void OnAssignedAtChanging(global::System.DateTime value);
        partial void OnAssignedAtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndedAt
        {
            get
            {
                return _EndedAt;
            }
            set
            {
                OnEndedAtChanging(value);
                ReportPropertyChanging("EndedAt");
                _EndedAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndedAt");
                OnEndedAtChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndedAt;
        partial void OnEndedAtChanging(Nullable<global::System.DateTime> value);
        partial void OnEndedAtChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DOSBModel", "FK_WorkshopAssignment_Employee", "Employee")]
        public Employee Employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DOSBModel.FK_WorkshopAssignment_Employee", "Employee").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DOSBModel.FK_WorkshopAssignment_Employee", "Employee").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> EmployeeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DOSBModel.FK_WorkshopAssignment_Employee", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("DOSBModel.FK_WorkshopAssignment_Employee", "Employee", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DOSBModel", "FK_WorkshopAssignment_WorkshopDailyActivity", "WorkshopDailyActivity")]
        public WorkshopDailyActivity WorkshopDailyActivity
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WorkshopDailyActivity>("DOSBModel.FK_WorkshopAssignment_WorkshopDailyActivity", "WorkshopDailyActivity").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WorkshopDailyActivity>("DOSBModel.FK_WorkshopAssignment_WorkshopDailyActivity", "WorkshopDailyActivity").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<WorkshopDailyActivity> WorkshopDailyActivityReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WorkshopDailyActivity>("DOSBModel.FK_WorkshopAssignment_WorkshopDailyActivity", "WorkshopDailyActivity");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<WorkshopDailyActivity>("DOSBModel.FK_WorkshopAssignment_WorkshopDailyActivity", "WorkshopDailyActivity", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DOSBModel", Name="WorkshopDailyActivity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WorkshopDailyActivity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WorkshopDailyActivity object.
        /// </summary>
        /// <param name="activityId">Initial value of the ActivityId property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="forklift">Initial value of the Forklift property.</param>
        /// <param name="torque">Initial value of the Torque property.</param>
        /// <param name="pressureTest">Initial value of the PressureTest property.</param>
        /// <param name="createdAt">Initial value of the CreatedAt property.</param>
        public static WorkshopDailyActivity CreateWorkshopDailyActivity(global::System.Int32 activityId, global::System.String description, global::System.Int32 forklift, global::System.Int32 torque, global::System.Int32 pressureTest, global::System.DateTime createdAt)
        {
            WorkshopDailyActivity workshopDailyActivity = new WorkshopDailyActivity();
            workshopDailyActivity.ActivityId = activityId;
            workshopDailyActivity.Description = description;
            workshopDailyActivity.Forklift = forklift;
            workshopDailyActivity.Torque = torque;
            workshopDailyActivity.PressureTest = pressureTest;
            workshopDailyActivity.CreatedAt = createdAt;
            return workshopDailyActivity;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ActivityId
        {
            get
            {
                return _ActivityId;
            }
            set
            {
                if (_ActivityId != value)
                {
                    OnActivityIdChanging(value);
                    ReportPropertyChanging("ActivityId");
                    _ActivityId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ActivityId");
                    OnActivityIdChanged();
                }
            }
        }
        private global::System.Int32 _ActivityId;
        partial void OnActivityIdChanging(global::System.Int32 value);
        partial void OnActivityIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Forklift
        {
            get
            {
                return _Forklift;
            }
            set
            {
                OnForkliftChanging(value);
                ReportPropertyChanging("Forklift");
                _Forklift = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Forklift");
                OnForkliftChanged();
            }
        }
        private global::System.Int32 _Forklift;
        partial void OnForkliftChanging(global::System.Int32 value);
        partial void OnForkliftChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Torque
        {
            get
            {
                return _Torque;
            }
            set
            {
                OnTorqueChanging(value);
                ReportPropertyChanging("Torque");
                _Torque = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Torque");
                OnTorqueChanged();
            }
        }
        private global::System.Int32 _Torque;
        partial void OnTorqueChanging(global::System.Int32 value);
        partial void OnTorqueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PressureTest
        {
            get
            {
                return _PressureTest;
            }
            set
            {
                OnPressureTestChanging(value);
                ReportPropertyChanging("PressureTest");
                _PressureTest = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PressureTest");
                OnPressureTestChanged();
            }
        }
        private global::System.Int32 _PressureTest;
        partial void OnPressureTestChanging(global::System.Int32 value);
        partial void OnPressureTestChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedAt
        {
            get
            {
                return _CreatedAt;
            }
            set
            {
                OnCreatedAtChanging(value);
                ReportPropertyChanging("CreatedAt");
                _CreatedAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedAt");
                OnCreatedAtChanged();
            }
        }
        private global::System.DateTime _CreatedAt;
        partial void OnCreatedAtChanging(global::System.DateTime value);
        partial void OnCreatedAtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FinishedAt
        {
            get
            {
                return _FinishedAt;
            }
            set
            {
                OnFinishedAtChanging(value);
                ReportPropertyChanging("FinishedAt");
                _FinishedAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FinishedAt");
                OnFinishedAtChanged();
            }
        }
        private Nullable<global::System.DateTime> _FinishedAt;
        partial void OnFinishedAtChanging(Nullable<global::System.DateTime> value);
        partial void OnFinishedAtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CanceledAt
        {
            get
            {
                return _CanceledAt;
            }
            set
            {
                OnCanceledAtChanging(value);
                ReportPropertyChanging("CanceledAt");
                _CanceledAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CanceledAt");
                OnCanceledAtChanged();
            }
        }
        private Nullable<global::System.DateTime> _CanceledAt;
        partial void OnCanceledAtChanging(Nullable<global::System.DateTime> value);
        partial void OnCanceledAtChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DOSBModel", "FK_WorkshopAssignment_WorkshopDailyActivity", "WorkshopAssignment")]
        public EntityCollection<WorkshopAssignment> WorkshopAssignment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<WorkshopAssignment>("DOSBModel.FK_WorkshopAssignment_WorkshopDailyActivity", "WorkshopAssignment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<WorkshopAssignment>("DOSBModel.FK_WorkshopAssignment_WorkshopDailyActivity", "WorkshopAssignment", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
